### ISSUE TITLE
Подготовительные работы : Создание заготовок контроллеров под новый функционал

### ISSUE THREAD

**Issue by SinitsaBogdan** [SinitsaBogdan/java-filmorate#6]
Создание новых контроллеров по шаблону проекта и ТЗ,
наполнение их базовыми методами для взаимодействия с системой.

В частности :

1. Контроллер для взаимодействия с Отзывами
2. Контроллер для взаимодействия с системой поиска
3. Контроллер для взаимодействия с Лентой событий
4. Контроллер по взаимодействию с Режиссёрами

**Comment by KonstantinTseplyaev** [comment]
проблемка в тестах гита при попытке pull request:  "Set the pull request to merge branch 'main' (instead of 'develop')
Задайте в Pull request ветку слияния 'main'  (вместо 'develop')
Error: Process completed with exit code 254."

**Comment by SinitsaBogdan** [comment]
feature: добавлен класс-контроллер SearchController("/films/search") и эндпоинт к нему: 

я думаю он должен быть не /films/search
а просто корневой /search

остальное смотрю

**Comment by SinitsaBogdan** [comment]
1) deleteToId - Удалить пользователя по идентификатору; 
Этот метод реализован
